footprint: [[ 0.57,  0.3], [-0.32,  0.3], [-0.32, -0.3], [ 0.57, -0.3]]
footprint_padding: 0.02
inflation_layer:
  inflation_radius: 0.55 # 2xfootprint, it helps to keep the global planned path farther from obstacles
transform_tolerance: 1

obstacle_layer:
  obstacle_range: 2.5
  raytrace_range: 3
  max_obstacle_height: 0.4
  track_unknown_space: true

  observation_sources: laser_scan_sensor point_cloud_sensorA point_cloud_sensorB

  laser_scan_sensor: {
    #may need a frame
    data_type: LaserScan,
    topic: scan,
    expected_update_rate: 0.2,
    marking: true,
    clearing: true
  }

  point_cloud_sensorA: {
    #probably need to change frame
    #sensor_frame: base_link,
    data_type: PointCloud2,
    topic: obstacles_cloud,
    expected_update_rate: 0.5,
    marking: true,
    clearing: true
    # min_obstacle_height: 0.04
  }

  point_cloud_sensorB: {
    #sensor_frame: base_link,
    data_type: PointCloud2,
    topic: ground_cloud,
    expected_update_rate: 0.5,
    marking: false,
    clearing: true
    # min_obstacle_height: -1.0 # make sure the ground is not filtered
  } 



#controller_patience: 2.0

#NavfnROS:
#    allow_unknown: true

#recovery_behaviors: [
#    {name: conservative_clear, type: clear_costmap_recovery/ClearCostmapRecovery},
#    {name: aggressive_clear, type: clear_costmap_recovery/ClearCostmapRecovery}
#]

#conservative_clear: 
#    reset_distance: 3.00
#aggressive_clear:
#    reset_distance: 1.84